name: flutter_template
description: flutter_template

publish_to: 'none'

version: 1.0.0+1 # 版本号

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 本地化
    sdk: flutter
  shared_preferences: ^2.0.11 # 数据持久化
  dio: ^4.0.4 # http
  flutter_easyloading: ^3.0.3 # loading 遮盖层

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: # flutter 相关的配置选项
  uses-material-design: true # 默认的 Material Design 字体图标

  assets: # 静态资源
    - assets/images/login/

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/icons/iconfont.ttf # 阿里矢量图标库提取的字体图标（该脚手架没有用这个，用的是 Flutter 自带的默认 icons）
